// ui.js
"use strict";
function renderSidebar() {
    const s = document.getElementById('sidebar'); if (!s) return;
    s.innerHTML = `
        <div class="flex items-center justify-center p-4 border-b border-slate-200 dark:border-slate-700">
            <img src="${CONFIG.APP_LOGO}" alt="Logo" class="h-10 w-10 mr-2 rounded-full"><h1 class="text-xl font-bold">I Expanse</h1>
        </div>
        <nav class="mt-4 flex-1">
            <a href="#" data-page="dashboard" class="nav-link flex items-center px-6 py-3 text-slate-700 dark:text-slate-300 hover:bg-teal-50 dark:hover:bg-teal-900/50"><i class='bx bxs-dashboard mr-3'></i> Dashboard</a>
            <a href="#" data-page="transactions" class="nav-link flex items-center px-6 py-3 text-slate-700 dark:text-slate-300 hover:bg-teal-50 dark:hover:bg-teal-900/50"><i class='bx bx-list-ul mr-3'></i> Transactions</a>
            <a href="#" data-page="reports" class="nav-link flex items-center px-6 py-3 text-slate-700 dark:text-slate-300 hover:bg-teal-50 dark:hover:bg-teal-900/50"><i class='bx bxs-report mr-3'></i> Reports</a>
            <a href="#" data-page="developer" class="nav-link flex items-center px-6 py-3 text-slate-700 dark:text-slate-300 hover:bg-teal-50 dark:hover:bg-teal-900/50"><i class='bx bx-code-alt mr-3'></i> Developer</a>
        </nav>
        <div class="p-4"><button id="theme-toggle" class="w-full flex items-center justify-center px-4 py-2 rounded-lg bg-slate-200 dark:bg-slate-700"><i class='bx ${state.settings.darkMode ? 'bxs-sun' : 'bxs-moon'} mr-2'></i><span>${state.settings.darkMode ? 'Light' : 'Dark'} Mode</span></button></div>`;
    document.getElementById('theme-toggle').onclick = toggleTheme;
}
function updateActiveNavLink() { document.querySelectorAll('.nav-link').forEach(link => { link.classList.toggle('bg-teal-50', link.dataset.page === state.ui.currentPage); link.classList.toggle('dark:bg-teal-900/50', link.dataset.page === state.ui.currentPage); link.classList.toggle('text-teal-600', link.dataset.page === state.ui.currentPage); link.classList.toggle('dark:text-teal-400', link.dataset.page === state.ui.currentPage); }); }
function renderPageTitle() { const title = state.ui.currentPage.charAt(0).toUpperCase() + state.ui.currentPage.slice(1); document.getElementById('page-title-container').innerHTML = `<h2>${title}</h2>`; }
function renderPageContent() {
    const content = document.getElementById('page-content');
    if (state.ui.currentPage === 'dashboard') content.innerHTML = getDashboardTemplate(); else if (state.ui.currentPage === 'transactions') content.innerHTML = getTransactionsTemplate(); else if (state.ui.currentPage === 'reports') content.innerHTML = getReportsTemplate(); else if (state.ui.currentPage === 'developer') content.innerHTML = getDeveloperTemplate();
    if (state.ui.currentPage === 'dashboard') renderDashboardData(); else if (state.ui.currentPage === 'transactions') renderTransactionsData(); else if (state.ui.currentPage === 'reports') renderReportsData(); else if (state.ui.currentPage === 'developer') renderDeveloperData();
}
function getDashboardTemplate() { return `<div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6"><div class="glass-card p-6 rounded-xl shadow-md"><p>Total Income</p><p id="total-income"></p></div><div class="glass-card p-6 rounded-xl shadow-md"><p>Total Expense</p><p id="total-expense"></p></div><div class="glass-card p-6 rounded-xl shadow-md"><p>Balance</p><p id="total-balance"></p></div></div><div class="glass-card p-6 rounded-xl shadow-md"><h3>Recent Transactions</h3><table class="w-full"><thead><tr><th>Desc.</th><th>Amount</th></tr></thead><tbody id="transaction-list"></tbody></table></div>`; }
function renderDashboardData() { const i = state.transactions.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0); const e = state.transactions.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0); document.getElementById('total-income').textContent=formatCurrency(i); document.getElementById('total-expense').textContent=formatCurrency(e); document.getElementById('total-balance').textContent=formatCurrency(i-e); document.getElementById('transaction-list').innerHTML = state.transactions.slice(0,5).map(t=>`<tr><td>${t.description}</td><td>${formatCurrency(t.amount)}</td></tr>`).join(''); }
function getTransactionsTemplate() { return `<div class="glass-card p-6 rounded-xl shadow-md"><table class="w-full"><thead><tr><th>Date</th><th>Desc.</th><th>Category</th><th>Amount</th><th>Actions</th></tr></thead><tbody id="transaction-table-body"></tbody></table></div>`; }
function renderTransactionsData() { document.getElementById('transaction-table-body').innerHTML = state.transactions.map(t=>`<tr><td>${new Date(t.date).toLocaleDateString()}</td><td>${t.description}</td><td>${getCategoryById(t.category,t.type)?.name}</td><td>${formatCurrency(t.amount)}</td><td><button onclick="openModal('${t.id}')">Edit</button><button onclick="deleteTransaction('${t.id}')">Del</button></td></tr>`).join(''); }
function getReportsTemplate() { return `<div class="glass-card p-6 rounded-xl shadow-md"><input type="date" id="date-from"><input type="date" id="date-to"><button id="generate-report-btn">Generate PDF</button><div class="h-80"><canvas id="expense-chart-report"></canvas></div></div>`; }
function renderReportsData() { document.getElementById('generate-report-btn').onclick = () => { const from = document.getElementById('date-from').value; const to = document.getElementById('date-to').value; generatePDF(from, to); }; }
function getDeveloperTemplate() { return `<div class="glass-card p-8 text-center"><img src="${CONFIG.DEVELOPER_PHOTO}" class="w-32 h-32 rounded-full mx-auto border-4 border-teal-500"><h2 class="text-2xl font-bold mt-4">${CONFIG.DEVELOPER_NAME}</h2><h3 class="text-teal-500">${CONFIG.DEVELOPER_TITLE}</h3><div id="social-links" class="flex justify-center space-x-4 mt-4"></div></div>`; }
function renderDeveloperData() { document.getElementById('social-links').innerHTML = `<a href="https://wa.me/${CONFIG.CONTACT.WHATSAPP}"><i class='bx bxl-whatsapp text-2xl'></i></a> <a href="${CONFIG.CONTACT.INSTAGRAM}"><i class='bx bxl-instagram text-2xl'></i></a>`; }
function openModal(id = null) { state.ui.editingTransactionId = id; const t = id ? state.transactions.find(t => t.id === id) : {}; document.getElementById('modal-container').innerHTML = `<div id="transaction-modal" class="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"><div class="bg-white dark:bg-slate-800 rounded-xl shadow-lg w-full max-w-md p-6"><h3 class="text-xl font-bold mb-4">${id ? 'Edit' : 'Add'} Transaction</h3><form id="transaction-form"> ... </form></div></div>`; document.getElementById('transaction-form').onsubmit = e => { e.preventDefault(); addOrUpdateTransaction({type: e.target.type.value, description: e.target.description.value, amount: e.target.amount.value, category: e.target.category.value, date: e.target.date.value}); }; }
function closeModal() { document.getElementById('modal-container').innerHTML = ''; }
function showToast(message, className) { const toast = document.createElement('div'); toast.className = `toast p-4 rounded-lg text-white shadow-lg mb-2 ${className}`; toast.textContent = message; document.getElementById('toast-container').appendChild(toast); setTimeout(() => toast.remove(), 3000); }